---
- name: install httpd
  yum: 
    name: httpd 
    state: installed

- name: set the httpd config
  template: 
    src: nextcloud.conf.j2 
    dest: /etc/httpd/conf.d/nextcloud.conf
  notify:
  - restart httpd
